### ISSUE TITLE
How  could I get the mock data?

### ISSUE THREAD

**Issue by yuwangjuan** [wqjiao/bpmn-activiti#1]
I can run the project ,but i dont get the mock data.so the project  is unabled for me . Could you please tell me how to run it ? I am absolutely  await your answer.

**Comment by Spareaftertaste** [comment]
what？ You can describe more detail. Maybe I can help you.

**Comment by wqjiao** [comment]
> I can run the project ,but i dont get the mock data.so the project is unabled for me . Could you please tell me how to run it ? I am absolutely await your answer.

In this path "bpmn-activiti/mock/", create the file and add the interface data

**Comment by wqjiao** [comment]
You pull down the code again.You can already see the mock data
