### ISSUE TITLE
编辑模式下（BpmnModeler）左侧的按钮图标显示不出来是怎么回事？

### ISSUE THREAD

**Issue by GitHub-zhangxy** [wqjiao/bpmn-activiti#10]
您好！执行您的程序，可正常运行，我将相关代码移植到另一个工程，想编辑流程图，发现左侧工具无图标，将工具拖到面板上，没办法链接两个流程节点。您是否能判断出问题大概出在哪里？
备注：
1、安装了
        "bpmn-js": "^5.0.3",
        "bpmn-js-properties-panel": "^0.32.1",
        "camunda-bpmn-moddle": "^4.1.2",
之前安装了较高版本的，发现运行失败，bpmn-js-properties-panel最新的版本与0.32.1相比，某些函数的入参有所改变，故把版本降了下来，可正常运行了，但流程节点拖到面板上后，周围的浮动操作按钮未显示出来，是否还有其他依赖？

**Comment by GitHub-zhangxy** [comment]
找到原因了，在common.css中引入的两个样式文件并没有被真正引入导致的。

**Comment by wqjiao** [comment]
好的
