### ISSUE TITLE
老哥，打扰下

### ISSUE THREAD

**Issue by lyxverycool** [wqjiao/bpmn-activiti#2]
老哥，打扰下，在搜webpack issues时看到 你提的webpackChunkName："name" * /,How to use variables for "name"?, for example:
这个问题最后解决了吗？虽然用了 [request] 这种，可以按照文件目录名打包，但是会包含**-index这种，名字太长了，有办法实现webpackChunkName：key.name 这种吗？

**Comment by lyxverycool** [comment]
> 老哥，打扰下，在搜webpack issues时看到 你提的webpackChunkName："name" * /,How to use variables for "name"?, for example:
> 这个问题最后解决了吗？虽然用了 [request] 这种，可以按照文件目录名打包，但是会包含**-index这种，名字太长了，有办法实现webpackChunkName：key.name 这种吗？

**Comment by wqjiao** [comment]
不好意思，才看到。是可以使用 `key.name` 的，但是对 `react-router` 的版本有要求 `v4.0+`，比如使用下面这种方式动态配置 `webpackChunkName`

```js
asyncComponent(() =>import(/* webpackChunkName: '`${name}`' */ `@/pages/${name}`))
```

**Comment by lyxverycool** [comment]
感谢老哥的回复，不过我之前也试过这样写。但是好像还是不行，打包出来大概是`${name}`92.52890f05.js 这样的，没有转义。
我用的是react-router-dom v5.0+ 跟这个应该没关系吧？然后用的@loadable/component异步加载。代码改成$name，大概如下
`import loadable from '@loadable/component'

export const loadableCom = (name) => loadable(() => import(/* webpackChunkName: '`${name}`' */`~/container/${name}/in`))

export const routes = [
  {
    path: ['/', '/index'],
    exact: true,
    requiresAuth: false,
    component: loadableCom('Index')
  },
  {
    path: '/datamonitor',
    exact: false,
    requiresAuth: false,
    component: loadableCom('DataMonitor')
  }]`
对了，好像看到webpack开发者回复说不支持 [https://github.com/webpack/webpack/issues/8444](url)

**Comment by wqjiao** [comment]
你这边的 ${name} 需要使用模板字符串包裹，不然它会识别成字符串 ${name}

**Comment by lyxverycool** [comment]
可能是编辑器的问题吧，我是用模板字符串包裹的。打包出来是`${name}`0.8ac1335b.js这种

**Comment by lyxverycool** [comment]
是编辑器的问题，我是使用模板字符串包裹的，github自动把`  `给去掉了。

**Comment by lyxverycool** [comment]
![2D935DEA-7AEB-425a-A563-F97D71D62D28](https://user-images.githubusercontent.com/25166423/88998349-64b3a680-d324-11ea-91d9-48ae656138e4.png)

**Comment by wqjiao** [comment]
我记得之前看过umi还是dva的源码，里面有这样的写法，之前截过图，但是现在找不到了，它里面就是用的变量
![umi-routes](https://user-images.githubusercontent.com/35959642/88998556-e6a3cf80-d324-11ea-8570-bce1affbaa2e.png)

**Comment by lyxverycool** [comment]
我大致明白它怎么改造的了，感谢老哥~

**Comment by wqjiao** [comment]
解决之后，记得分享一波哦，期待~~~
