### ISSUE TITLE
npm start 报错

### ISSUE THREAD

**Issue by ShichengBegonia** [wqjiao/bpmn-activiti#8]
![image](https://user-images.githubusercontent.com/6166544/89771333-b6351000-db32-11ea-8b32-42f85f836cbd.png)

## 错误原因

构建 dll 文件时出错了，由于 dependencies 下的依赖会全部被打到 dll 里，所以报错可能有以下原因：

    1. dependencies 里的某些依赖没有 main 文件
    2. 应该放在 devDependencies 里的 node 相关的依赖却写在了 dependencies

## 解决方案

让不该打到 dll 的不被打到 dll 里，有几个解决方案：

    1. 把 node 相关依赖放到 devDependencies 里
    2. 把出错的依赖配置到 dll 的 exclude 里

比如：

    dll: {
      exclude: ['foo']
    }

**Comment by wqjiao** [comment]
使用yarn安装依赖，然后运行 yarn start 哈

**Comment by ShichengBegonia** [comment]
这个问题好了

**Comment by BaLaLaLs** [comment]
怎么解决的我也遇到了相同的问题
