### ISSUE TITLE
缺少内容

### ISSUE THREAD

**Issue by ShichengBegonia** [wqjiao/bpmn-activiti#9]
请问你的demo 包含 左边 中间画布 还有右边属性 这三块内容么？ 为什么我跑了你的actice demo 只有画布的内容呢

**Comment by wqjiao** [comment]
我这边展示是正常的呢(包括左边工具栏、画布、右边表单、悬浮的操作栏)
 https://github.com/wqjiao/bpmn-activiti/blob/master/public/bpmn.gif
